In [1]:
 import numpy as np

In [2]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# where

In [3]:
a=np.array([1,2,3,4])
b=np.array([100,200,300,400])
c=np.array([True,False,True,False])

In [4]:
np.where(c,a,b)

array([  1, 200,   3, 400])

In [5]:
c1=np.array([True,True,False,True])

In [6]:
np.where(c1,b,a)

array([100, 200,   3, 400])

# Second use of where

In [7]:
np.random.seed(1)
mse1=np.random.randint(1,101,10)
mse1

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [8]:
np.where(mse1<40) # will  give index value where condition is true

(array([0, 1, 3, 5, 8, 9], dtype=int64),)

In [9]:
np.where(mse1<40,40,mse1)

array([40, 40, 73, 40, 76, 40, 80, 65, 40, 40])

# Pandas

In [10]:
import pandas as pd

In [11]:
from pandas import Series

In [12]:
ser1=Series([10,20,30,40])
ser1

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
Ser1=Series([10,20,30,40],index=['A','B','C','D'])
Ser1

A    10
B    20
C    30
D    40
dtype: int64

In [14]:
Ser1.values

array([10, 20, 30, 40], dtype=int64)

In [15]:
Ser1.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [16]:
ser2=Series({'A':'Alpha','B':'Beta'})
ser2

A    Alpha
B     Beta
dtype: object

In [17]:
ser3=Series(np.random.randint(1,19,5))
ser3

0    13
1     8
2    14
3     7
4     6
dtype: int32

In [18]:
ser3=Series(np.random.randint(1,19,5),range(1,6)) #no need to write index it isbydefault at position 2
ser3

1    12
2    11
3    15
4     5
5    10
dtype: int32

In [19]:
ser1=Series([10,20,30,40,50,60],list("ABCDEF"))
ser1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [20]:
list('ABCDEF')

['A', 'B', 'C', 'D', 'E', 'F']

# INDEXING

# Grab by Index

In [21]:
ser1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [22]:
ser1[0]

10

In [23]:
ser1[-1]

60

# Grab by Label

In [24]:
ser1['A']

10

In [25]:
ser1['D']

40

# Grab by Multiple Label/Index

In [26]:
ser1[['A','D']] #for multiple values make sure you pass index in a list

A    10
D    40
dtype: int64

In [27]:
ser1[[0,1]]

A    10
B    20
dtype: int64

# Grab by Range of Index

In [28]:
ser1[:3]

A    10
B    20
C    30
dtype: int64

In [29]:
ser1[::2]

A    10
C    30
E    50
dtype: int64

# Grab by Logic

In [30]:
ser1

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

In [31]:
ser1<35

A     True
B     True
C     True
D    False
E    False
F    False
dtype: bool

In [32]:
ser1[ser1<35]

A    10
B    20
C    30
dtype: int64

In [33]:
(ser1>20) & (ser1<55)

A    False
B    False
C     True
D     True
E     True
F    False
dtype: bool

In [34]:
ser1[(ser1>20) & (ser1<55)]

C    30
D    40
E    50
dtype: int64

In [35]:
(ser1>20) | (ser1<55)

A    True
B    True
C    True
D    True
E    True
F    True
dtype: bool

In [36]:
ser1[(ser1>20) | (ser1<55 )] #either of condition should true

A    10
B    20
C    30
D    40
E    50
F    60
dtype: int64

# DataFrame

In [37]:
import numpy as np
from pandas import Series,DataFrame

In [38]:
df1=DataFrame(np.arange(1,26).reshape(5,5))

df1

0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25

In [39]:
df1=DataFrame(np.arange(1,26).reshape(5,5),index=list('ABCDE'))
df1

0   1   2   3   4
A   1   2   3   4   5
B   6   7   8   9  10
C  11  12  13  14  15
D  16  17  18  19  20
E  21  22  23  24  25

In [40]:
df1=DataFrame(np.arange(1,26).reshape(5,5),index=list("ABCDE"),
              columns=['col1','col2','col3','col4','col5'])
df1

col1  col2  col3  col4  col5
A     1     2     3     4     5
B     6     7     8     9    10
C    11    12    13    14    15
D    16    17    18    19    20
E    21    22    23    24    25

In [41]:
df1.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')

In [42]:
df1.columns

Index(['col1', 'col2', 'col3', 'col4', 'col5'], dtype='object')

In [43]:
df1.columns[-1]

'col5'

In [44]:
df1.values

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [45]:
for i in df1.columns:
    print('column name is:',i)

column name is: col1
column name is: col2
column name is: col3
column name is: col4
column name is: col5


# Further ways to create DataFrame

In [46]:
df2=DataFrame([['Aniruddha','Kalbannde' ,100,'Male'],
               ['Shreya','Jain',18,'Female']],columns=['First Name','Last Name','Age','Gender'],index=[1,2])

In [47]:
df2

First Name  Last Name  Age  Gender
1  Aniruddha  Kalbannde  100    Male
2     Shreya       Jain   18  Female

In [48]:
gender=["Male","Female"]

In [49]:
df3=DataFrame({'Name':['Aniruddha kalbande',"Shreya Jain"],
               'Age':[10,20],
                'Gender':gender})
df3


Name  Age  Gender
0  Aniruddha kalbande   10    Male
1         Shreya Jain   20  Female

In [50]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    2 non-null      object
 1   Age     2 non-null      int64 
 2   Gender  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 176.0+ bytes


In [51]:
df3.dtypes

Name      object
Age        int64
Gender    object
dtype: object

In [52]:
#df1=pd.read_csv('filename.csv')
df2.to_csv('filename.csv',index=False) #creating a csv(comma seperated values) file
#if we dont give index false it will generate dafault index

In [53]:
df4=pd.read_csv('filename.csv')
df4

First Name  Last Name  Age  Gender
0  Aniruddha  Kalbannde  100    Male
1     Shreya       Jain   18  Female

In [54]:
company=['Tata','Facebook','Google','Wipro','Infosys']
ticker=['TCS','FB','GOOG','WIP','INFY']
np.random.seed(1)
price=np.random.randint(500,5000,5)
df5=DataFrame({'Company':company,'ticker':ticker,'price':price})
df5

Company ticker  price
0      Tata    TCS    735
1  Facebook     FB   4480
2    Google   GOOG   1405
3     Wipro    WIP   3263
4   Infosys   INFY   3395

# Grab by Column Name

In [55]:
df1["col1"]

A     1
B     6
C    11
D    16
E    21
Name: col1, dtype: int32

# Grab by Multiple Column

In [56]:
df1[['col1','col5']]

col1  col5
A     1     5
B     6    10
C    11    15
D    16    20
E    21    25

# Grab by Range Index

In [57]:
df1[1:3]

col1  col2  col3  col4  col5
B     6     7     8     9    10
C    11    12    13    14    15

# Grab by Logic

In [58]:
df1["col1"]

A     1
B     6
C    11
D    16
E    21
Name: col1, dtype: int32

In [59]:
df1['col1']<10

A     True
B     True
C    False
D    False
E    False
Name: col1, dtype: bool

In [60]:
df1[df1['col1']<10]

col1  col2  col3  col4  col5
A     1     2     3     4     5
B     6     7     8     9    10

In [61]:
df1[df1['col1']<10]['col1']


A    1
B    6
Name: col1, dtype: int32

In [62]:
df1[df1['col1']<10][['col2','col3']]

col2  col3
A     2     3
B     7     8

In [63]:
df5[df5['price']<1000]

Company ticker  price
0    Tata    TCS    735

In [64]:
df5[df5['price']<1000]['ticker']

0    TCS
Name: ticker, dtype: object

In [65]:
df5[(df5['price']<3000) &(df5['price']>1000)]

Company ticker  price
2  Google   GOOG   1405

# iloc and loc

In [66]:
df1.iloc[0]

col1    1
col2    2
col3    3
col4    4
col5    5
Name: A, dtype: int32

In [67]:
df1.iloc[[0]]

col1  col2  col3  col4  col5
A     1     2     3     4     5

In [68]:
df1.iloc[0,0]

1

In [69]:
df1.iloc[:,1]

A     2
B     7
C    12
D    17
E    22
Name: col2, dtype: int32

In [70]:
df1.iloc[:3,:3]

col1  col2  col3
A     1     2     3
B     6     7     8
C    11    12    13

In [71]:
df1.iloc[:,[0,2,1]]

col1  col3  col2
A     1     3     2
B     6     8     7
C    11    13    12
D    16    18    17
E    21    23    22

# loc is Label based

In [72]:
df1.loc[['A']]

col1  col2  col3  col4  col5
A     1     2     3     4     5

In [73]:
df1.loc['A'] #bydefault but we can trcik by applying nested list

col1    1
col2    2
col3    3
col4    4
col5    5
Name: A, dtype: int32

In [74]:
df1.loc['A','col1']

1

In [75]:
df1.loc[:,'col1']

A     1
B     6
C    11
D    16
E    21
Name: col1, dtype: int32

In [76]:
 df1.loc[:,['col1','col3']]

col1  col3
A     1     3
B     6     8
C    11    13
D    16    18
E    21    23

In [77]:
#df1.iloc[[0,2,1]]

In [78]:
df5

Company ticker  price
0      Tata    TCS    735
1  Facebook     FB   4480
2    Google   GOOG   1405
3     Wipro    WIP   3263
4   Infosys   INFY   3395

In [79]:
df5['country']='India'
df5

Company ticker  price country
0      Tata    TCS    735   India
1  Facebook     FB   4480   India
2    Google   GOOG   1405   India
3     Wipro    WIP   3263   India
4   Infosys   INFY   3395   India

In [80]:
df5['country']=['India','USA','USA','India','India']
df5

Company ticker  price country
0      Tata    TCS    735   India
1  Facebook     FB   4480     USA
2    Google   GOOG   1405     USA
3     Wipro    WIP   3263   India
4   Infosys   INFY   3395   India

In [81]:
df5['price+GST']=df5['price']*1.18
df5

Company ticker  price country  price+GST
0      Tata    TCS    735   India     867.30
1  Facebook     FB   4480     USA    5286.40
2    Google   GOOG   1405     USA    1657.90
3     Wipro    WIP   3263   India    3850.34
4   Infosys   INFY   3395   India    4006.10

In [82]:
df=DataFrame({'Name':['Ankit','Rahul','Shreya','Roshni'],
            'Marks':[5,20,19,35]})
df

Name  Marks
0   Ankit      5
1   Rahul     20
2  Shreya     19
3  Roshni     35

# SORTING

In [83]:
np.random.seed(0)
ser1=Series(np.random.randint(1,100,10))
ser1

0    45
1    48
2    65
3    68
4    68
5    10
6    84
7    22
8    37
9    88
dtype: int32

In [84]:
ser1.sort_values() #in ascending order

5    10
7    22
8    37
0    45
1    48
2    65
3    68
4    68
6    84
9    88
dtype: int32

In [85]:
ser1.sort_values(ascending=False) #in descending order

9    88
6    84
3    68
4    68
2    65
1    48
0    45
8    37
7    22
5    10
dtype: int32

In [86]:
ser1 #no change will occue in original variable

0    45
1    48
2    65
3    68
4    68
5    10
6    84
7    22
8    37
9    88
dtype: int32

In [87]:
 ser1.sort_values(ascending=False,inplace=True)

In [88]:
ser1

9    88
6    84
3    68
4    68
2    65
1    48
0    45
8    37
7    22
5    10
dtype: int32

In [89]:
df1=DataFrame({'Name':['Ankit','Rahul','Shreya','Rashmi'],
               'Marks':[5,20,19,35]})

In [90]:
df1

Name  Marks
0   Ankit      5
1   Rahul     20
2  Shreya     19
3  Rashmi     35

In [91]:
df1.sort_values(by='Marks')

Name  Marks
0   Ankit      5
2  Shreya     19
1   Rahul     20
3  Rashmi     35

In [92]:
df1.sort_values(by='Marks',ascending=False)

Name  Marks
3  Rashmi     35
1   Rahul     20
2  Shreya     19
0   Ankit      5

In [93]:
df1['Marks2']=[10,55,20,25]
df1

Name  Marks  Marks2
0   Ankit      5      10
1   Rahul     20      55
2  Shreya     19      20
3  Rashmi     35      25

In [94]:
df1.iloc[2,1]=20
df1

Name  Marks  Marks2
0   Ankit      5      10
1   Rahul     20      55
2  Shreya     20      20
3  Rashmi     35      25

In [95]:
df1.sort_values(by=['Marks','Marks2'],ascending=[True,False])

Name  Marks  Marks2
0   Ankit      5      10
1   Rahul     20      55
2  Shreya     20      20
3  Rashmi     35      25

In [96]:
df1=df1.sort_values(by=['Marks','Marks2'],ascending=[False,True])
df1

Name  Marks  Marks2
3  Rashmi     35      25
2  Shreya     20      20
1   Rahul     20      55
0   Ankit      5      10

In [97]:
df1.sort_index()

Name  Marks  Marks2
0   Ankit      5      10
1   Rahul     20      55
2  Shreya     20      20
3  Rashmi     35      25

# Ranks in DataFrame

In [98]:
df1=DataFrame({'Name':['Ankit','Rahul','Shreya','Rashmi'],'Marks':[5,20,20,35]})
df1

Name  Marks
0   Ankit      5
1   Rahul     20
2  Shreya     20
3  Rashmi     35

In [99]:
df1['Rank Avg']=df1['Marks'].rank()
df1['Rank Min']=df1['Marks'].rank(method='min')
df1['Rank Max']=df1['Marks'].rank(method='max')
df1['Rank Dense']=df1['Marks'].rank(method='dense')
df1['Rank First']=df1['Marks'].rank(method='first')
df1['Rank Rev Avg']=df1['Marks'].rank(ascending=False)
df1

Name  Marks  Rank Avg  Rank Min  Rank Max  Rank Dense  Rank First  \
0   Ankit      5       1.0       1.0       1.0         1.0         1.0   
1   Rahul     20       2.5       2.0       3.0         2.0         2.0   
2  Shreya     20       2.5       2.0       3.0         2.0         3.0   
3  Rashmi     35       4.0       4.0       4.0         3.0         4.0   

   Rank Rev Avg  
0           4.0  
1           2.5  
2           2.5  
3           1.0

In [100]:
df=DataFrame({'Name':['Aniruddh kalbande','Shreya Jain'],'Age':[100,56]}) 
df

Name  Age
0  Aniruddh kalbande  100
1        Shreya Jain   56

In [101]:
df['Name'].str.split(expand=True)

0         1
0  Aniruddh  kalbande
1    Shreya      Jain

In [102]:
df[['FN','LN']]=df['Name'].str.split(expand
                                     =True)
df

Name  Age        FN        LN
0  Aniruddh kalbande  100  Aniruddh  kalbande
1        Shreya Jain   56    Shreya      Jain