In [3]:
import numpy as np


In [4]:
l1=[1,2,3,]
arr1=np.array(l1)
print(arr1)

[1 2 3]


In [5]:
arr1

array([1, 2, 3])

In [6]:
type(arr1)

numpy.ndarray

In [9]:
l1=[1,2,3]
l2=[10,20,30]

In [11]:
l=[l1,l2]
l

[[1, 2, 3], [10, 20, 30]]

In [12]:
arr2d=np.array(l)
arr2d

array([[ 1,  2,  3],
       [10, 20, 30]])

In [13]:
arr1.ndim

1

In [14]:
arr2d.ndim

2

In [15]:
arr1.shape

(3,)

In [16]:
arr2d.shape

(2, 3)

In [17]:
arr2d.shape[0] #row

2

In [18]:
arr2d.shape[1] #column

3

In [19]:
lst=[5,8,3,2]

In [20]:
arr2=np.array(lst)
print(arr2)

[5 8 3 2]


In [5]:
arr3=np.array([[10,20,15],[2,5,8],[9,10,3]])
print(arr3)

[[10 20 15]
 [ 2  5  8]
 [ 9 10  3]]


In [22]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
np.arange(2,5)

array([2, 3, 4])

In [24]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
#array of (3,4) odd numbers 
np.arange(1,25,2).reshape(3,4)

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [28]:
a=[10,20,30,40]
b=[[10,20,30],[40,50,60],[70,80,90]]
a=np.array(a)
print(a)

b=np.array(b)
print(b)

[10 20 30 40]
[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [29]:
a[0]

10

In [30]:
a[:]

array([10, 20, 30, 40])

In [31]:
a[2:]

array([30, 40])

In [32]:
a[:2]

array([10, 20])

In [49]:
a[::2]

array([10, 30])

In [33]:
a[1::2]

array([20, 40])

In [34]:
a[::-1]

array([40, 30, 20, 10])

In [35]:
b[0]

array([10, 20, 30])

In [36]:
b[-1]

array([70, 80, 90])

In [37]:
b[:2]

array([[10, 20, 30],
       [40, 50, 60]])

In [38]:
b[1:]

array([[40, 50, 60],
       [70, 80, 90]])

In [39]:
b[::-1]

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])

In [40]:
b[::-2]

array([[70, 80, 90],
       [10, 20, 30]])

In [41]:
b[0,0]

10

In [42]:
b[0,:2]

array([10, 20])

In [43]:
b[:,1]

array([20, 50, 80])

In [45]:
b[1:,:2]

array([[40, 50],
       [70, 80]])

In [46]:
c=np.arange(1,101).reshape(10,10)
print(c)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [47]:
c[1]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [48]:
c[:,7]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [49]:
c[5:7,7:]

array([[58, 59, 60],
       [68, 69, 70]])

In [50]:
c[2:7:2,3:7]

array([[24, 25, 26, 27],
       [44, 45, 46, 47],
       [64, 65, 66, 67]])

In [51]:
c[-8:-3:2,-7:-3]

array([[24, 25, 26, 27],
       [44, 45, 46, 47],
       [64, 65, 66, 67]])

In [52]:
#fancy indexing
c[[1,2,2,3,5]]

array([[11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [51, 52, 53, 54, 55, 56, 57, 58, 59, 60]])

In [53]:
c[:,[1,2,3,3,8]]

array([[ 2,  3,  4,  4,  9],
       [12, 13, 14, 14, 19],
       [22, 23, 24, 24, 29],
       [32, 33, 34, 34, 39],
       [42, 43, 44, 44, 49],
       [52, 53, 54, 54, 59],
       [62, 63, 64, 64, 69],
       [72, 73, 74, 74, 79],
       [82, 83, 84, 84, 89],
       [92, 93, 94, 94, 99]])

In [54]:
c[[1,2],[1,2]]

array([12, 23])

In [55]:
c[[1],[1]]

array([12])

In [56]:
c[:,[2]]

array([[ 3],
       [13],
       [23],
       [33],
       [43],
       [53],
       [63],
       [73],
       [83],
       [93]])

In [146]:
c[[1,2],[1,3]] #list one has rows and list two has columns

array([12, 24])

# aritematic operators

In [58]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [59]:
a+10

array([11, 12, 13, 14])

In [60]:
a*2

array([2, 4, 6, 8])

In [61]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [62]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [63]:
a//2

array([0, 1, 1, 2], dtype=int32)

In [64]:
1/a

array([1.        , 0.5       , 0.33333333, 0.25      ])

In [65]:
d=[10,20,30,40]
d=np.array(d)
d

array([10, 20, 30, 40])

In [66]:
a

array([1, 2, 3, 4])

In [67]:
d

array([10, 20, 30, 40])

In [68]:
a+d

array([11, 22, 33, 44])

In [69]:
a-d

array([ -9, -18, -27, -36])

In [70]:
a*d

array([ 10,  40,  90, 160])

In [71]:
a**d #have to change the format 

array([          1,     1048576, -1010140999,           0], dtype=int32)

# Relational operators

In [72]:
a

array([1, 2, 3, 4])

In [73]:
a<2

array([ True, False, False, False])

In [74]:
a!=2

array([ True, False,  True,  True])

# functions in numpy

In [75]:
a

array([1, 2, 3, 4])

In [76]:
np.mean(a)

2.5

In [77]:
np.sum(a)

10

In [79]:
np.std(a)

1.118033988749895

In [80]:
np.var(a)

1.25

In [81]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [82]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

# Concept of Axis

In [83]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
np.mean(a)

5.0

In [85]:
np.mean(a,axis=0) #vertically

array([4., 5., 6.])

In [86]:
np.mean(a,axis=1) #horizontally

array([2., 5., 8.])

In [87]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
np.sum(a)

45

In [89]:
np.sum(a,axis=0)

array([12, 15, 18])

In [90]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [91]:
a.sum() #can also be performed like this

45

In [92]:
a.sum(axis=1)

array([ 6, 15, 24])

In [94]:
a.T #transpose of matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [95]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [97]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [98]:
np.zeros([3,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [99]:
np.ones([3,3],dtype=int)*3

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

# Generating random numbers

In [102]:
from numpy.random import randint

In [103]:
randint(1,101,10)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [104]:
randint(1,101,10)


array([71, 89, 89, 13, 59, 66, 40, 88, 47, 89])

In [105]:
a=np.random.rand(100)
a

array([0.3927848 , 0.83607876, 0.33739616, 0.64817187, 0.36824154,
       0.95715516, 0.14035078, 0.87008726, 0.47360805, 0.80091075,
       0.52047748, 0.67887953, 0.72063265, 0.58201979, 0.53737323,
       0.75861562, 0.10590761, 0.47360042, 0.18633234, 0.73691818,
       0.21655035, 0.13521817, 0.32414101, 0.14967487, 0.22232139,
       0.38648898, 0.90259848, 0.44994999, 0.61306346, 0.90234858,
       0.09928035, 0.96980907, 0.65314004, 0.17090959, 0.35815217,
       0.75068614, 0.60783067, 0.32504723, 0.03842543, 0.63427406,
       0.95894927, 0.65279032, 0.63505887, 0.99529957, 0.58185033,
       0.41436859, 0.4746975 , 0.6235101 , 0.33800761, 0.67475232,
       0.31720174, 0.77834548, 0.94957105, 0.66252687, 0.01357164,
       0.6228461 , 0.67365963, 0.971945  , 0.87819347, 0.50962438,
       0.05571469, 0.45115921, 0.01998767, 0.44171092, 0.97958673,
       0.35944446, 0.48089353, 0.68866118, 0.88047589, 0.91823547,
       0.21682214, 0.56518887, 0.86510256, 0.50896896, 0.91672

In [106]:
a.mean()

0.5431137078282469

# Concept of Seeds

In [107]:
np.random.seed(0) #after using seed output value will be random but same for same value of seed
randint(1,101,10)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [108]:
np.random.seed(0)
randint(1,101,10)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [109]:
np.random.seed(1)
randint(1,101,10)

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [110]:
np.random.seed(1)
randint(1,101,10)

array([38, 13, 73, 10, 76,  6, 80, 65, 17,  2])

In [111]:
np.random.seed(0) 
marks=randint(1,101,10)
marks

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [112]:
marks<40


array([False, False, False, False, False,  True, False,  True,  True,
       False])

In [113]:
marks[marks<40]#2d array will give only boolean output but it will not give actual value

array([10, 22, 37])

# Concatenation

In [9]:
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])


In [11]:
np.concatenate([a,b])

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [18]:
np.concatenate([a,b],axis=0)

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [123]:
a1=np.arange(1,7).reshape(2,3)
b1=a1+10


In [124]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [125]:
b1

array([[11, 12, 13],
       [14, 15, 16]])

In [126]:
np.concatenate([a1,b1])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [127]:
np.concatenate([a1,b1],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [128]:
np.concatenate([a1,b1],axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

# Stacking

In [129]:
a

array([1, 2, 3, 4])

In [130]:
b

array([10, 20, 30, 40])

In [131]:
np.stack([a,b])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [133]:
np.hstack([a,b])

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [134]:
np.vstack([a,b])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [135]:
np.column_stack([a,b])

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

In [136]:
a3d=np.dstack([a,b])
a3d

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30],
        [ 4, 40]]])

In [137]:
a3d.ndim

3

# Splitting

In [138]:
a=np.arange(1,9).reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [139]:
np.hsplit(a,2) #horizontal splitting

[array([[1, 2],
        [5, 6]]),
 array([[3, 4],
        [7, 8]])]

In [140]:
np.hsplit(a,2)[0]

array([[1, 2],
       [5, 6]])

In [141]:
np.hsplit(a,2)[1]

array([[3, 4],
       [7, 8]])

In [143]:
np.vsplit(a,2) #Vertical splitting

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]

# Loops in Array

In [144]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [145]:
for i in a:
    print(i)

[1 2 3 4]
[5 6 7 8]


In [186]:
for i in a:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
